[[classOrder]]
classes = ["Util"]

[[classOrder]]
section = "Components"
classes = [
  "Base",
  "Button",
  "Frame",
  "BaseButton",
  "IconButton",
  "Card",
  "Group",
  "Switch",
  "Text",
  "Badge",
  "Scroller",
  "Checkbox",
  "TextInput",
  "TextArea",
  "Avatar",
  "ProgressBar",
  "TitleBar",
  "Icon",
  "Divider",
  "AutoScaler",
  "Image",
  "IconText",
  "Heading",
  "TextSwap",
  "Slider",
]

[docusaurus]
title = "OnyxUI"
tagline = "Quick, customizable components for Fusion"
url = "https://loneka.com/"
favicon = "/favicon.svg"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "High quality components 🧩"
description = "Make quality UI faster with dozens of fully-typed components."

[[home.features]]
title = "Comprehensive theming 🎨"
description = "Give your UI the look and feel you desire with ease."

[[home.features]]
title = "Styling, now *not* stupid 🖌️"
description = "Screw messy markup. Style any component, with less code, using OnyxUI's passthrough styling props."

[[navbar.items]]
href = "https://loneka.com/suite/discord"
label = "Discord"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2025 Avafe. Built with Moonwave and Docusaurus"

# [[classOrder]]
# section = "Util"
# collapsed = true
# classes = ["Colors", "EnsureValue"]
