[dependencies]
ColorUtils = "csqrl/colour-utils@^1.4.1"
Fusion = "elttob/fusion@^0.3.0"
Signal = "sleitnick/signal@^2.0.1"

[package]
authors = ["Avafe"]
license = "MIT"
name = "imavafe/onyx-ui"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.6.0"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]
